// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: funapi/rpc/fun_dedicated_server_rpc_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "funapi/rpc/fun_dedicated_server_rpc_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* FunDedicatedServerRpcMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunDedicatedServerRpcMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* FunDedicatedServerRpcInfoMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunDedicatedServerRpcInfoMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto() {
  protobuf_AddDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "funapi/rpc/fun_dedicated_server_rpc_message.proto");
  GOOGLE_CHECK(file != NULL);
  FunDedicatedServerRpcMessage_descriptor_ = file->message_type(0);
  static const int FunDedicatedServerRpcMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcMessage, xid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcMessage, type_),
  };
  FunDedicatedServerRpcMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FunDedicatedServerRpcMessage_descriptor_,
      FunDedicatedServerRpcMessage::default_instance_,
      FunDedicatedServerRpcMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcMessage, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcMessage, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FunDedicatedServerRpcMessage));
  FunDedicatedServerRpcInfoMessage_descriptor_ = file->message_type(1);
  static const int FunDedicatedServerRpcInfoMessage_offsets_[1] = {
  };
  FunDedicatedServerRpcInfoMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FunDedicatedServerRpcInfoMessage_descriptor_,
      FunDedicatedServerRpcInfoMessage::default_instance_,
      FunDedicatedServerRpcInfoMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcInfoMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunDedicatedServerRpcInfoMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FunDedicatedServerRpcInfoMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FunDedicatedServerRpcMessage_descriptor_, &FunDedicatedServerRpcMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FunDedicatedServerRpcInfoMessage_descriptor_, &FunDedicatedServerRpcInfoMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto() {
  delete FunDedicatedServerRpcMessage::default_instance_;
  delete FunDedicatedServerRpcMessage_reflection_;
  delete FunDedicatedServerRpcInfoMessage::default_instance_;
  delete FunDedicatedServerRpcInfoMessage_reflection_;
}

void protobuf_AddDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n1funapi/rpc/fun_dedicated_server_rpc_me"
    "ssage.proto\"C\n\034FunDedicatedServerRpcMess"
    "age\022\013\n\003xid\030\001 \002(\014\022\014\n\004type\030\002 \002(\t*\010\010\010\020\200\200\200\200\002"
    "\"\"\n FunDedicatedServerRpcInfoMessage:Q\n\007"
    "ds_info\022\035.FunDedicatedServerRpcMessage\030\010"
    " \001(\0132!.FunDedicatedServerRpcInfoMessage", 239);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "funapi/rpc/fun_dedicated_server_rpc_message.proto", &protobuf_RegisterTypes);
  FunDedicatedServerRpcMessage::default_instance_ = new FunDedicatedServerRpcMessage();
  FunDedicatedServerRpcInfoMessage::default_instance_ = new FunDedicatedServerRpcInfoMessage();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::FunDedicatedServerRpcMessage::default_instance(),
    8, 11, false, false,
    &::FunDedicatedServerRpcInfoMessage::default_instance());
  FunDedicatedServerRpcMessage::default_instance_->InitAsDefaultInstance();
  FunDedicatedServerRpcInfoMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto {
  StaticDescriptorInitializer_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto() {
    protobuf_AddDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto();
  }
} static_descriptor_initializer_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FunDedicatedServerRpcMessage::kXidFieldNumber;
const int FunDedicatedServerRpcMessage::kTypeFieldNumber;
#endif  // !_MSC_VER

FunDedicatedServerRpcMessage::FunDedicatedServerRpcMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FunDedicatedServerRpcMessage)
}

void FunDedicatedServerRpcMessage::InitAsDefaultInstance() {
}

FunDedicatedServerRpcMessage::FunDedicatedServerRpcMessage(const FunDedicatedServerRpcMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FunDedicatedServerRpcMessage)
}

void FunDedicatedServerRpcMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  xid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FunDedicatedServerRpcMessage::~FunDedicatedServerRpcMessage() {
  // @@protoc_insertion_point(destructor:FunDedicatedServerRpcMessage)
  SharedDtor();
}

void FunDedicatedServerRpcMessage::SharedDtor() {
  if (xid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete xid_;
  }
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (this != default_instance_) {
  }
}

void FunDedicatedServerRpcMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunDedicatedServerRpcMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunDedicatedServerRpcMessage_descriptor_;
}

const FunDedicatedServerRpcMessage& FunDedicatedServerRpcMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto();
  return *default_instance_;
}

FunDedicatedServerRpcMessage* FunDedicatedServerRpcMessage::default_instance_ = NULL;

FunDedicatedServerRpcMessage* FunDedicatedServerRpcMessage::New() const {
  return new FunDedicatedServerRpcMessage;
}

void FunDedicatedServerRpcMessage::Clear() {
  _extensions_.Clear();
  if (_has_bits_[0 / 32] & 3) {
    if (has_xid()) {
      if (xid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        xid_->clear();
      }
    }
    if (has_type()) {
      if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        type_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FunDedicatedServerRpcMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FunDedicatedServerRpcMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes xid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_xid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_type;
        break;
      }

      // required string type = 2;
      case 2: {
        if (tag == 18) {
         parse_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        if ((64u <= tag)) {
          DO_(_extensions_.ParseField(tag, input, default_instance_,
                                      mutable_unknown_fields()));
          continue;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FunDedicatedServerRpcMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FunDedicatedServerRpcMessage)
  return false;
#undef DO_
}

void FunDedicatedServerRpcMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FunDedicatedServerRpcMessage)
  // required bytes xid = 1;
  if (has_xid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->xid(), output);
  }

  // required string type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->type(), output);
  }

  // Extension range [8, 536870912)
  _extensions_.SerializeWithCachedSizes(
      8, 536870912, output);

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FunDedicatedServerRpcMessage)
}

::google::protobuf::uint8* FunDedicatedServerRpcMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FunDedicatedServerRpcMessage)
  // required bytes xid = 1;
  if (has_xid()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->xid(), target);
  }

  // required string type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->type(), target);
  }

  // Extension range [8, 536870912)
  target = _extensions_.SerializeWithCachedSizesToArray(
      8, 536870912, target);

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FunDedicatedServerRpcMessage)
  return target;
}

int FunDedicatedServerRpcMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes xid = 1;
    if (has_xid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->xid());
    }

    // required string type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type());
    }

  }
  total_size += _extensions_.ByteSize();

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunDedicatedServerRpcMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FunDedicatedServerRpcMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FunDedicatedServerRpcMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunDedicatedServerRpcMessage::MergeFrom(const FunDedicatedServerRpcMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_xid()) {
      set_xid(from.xid());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FunDedicatedServerRpcMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunDedicatedServerRpcMessage::CopyFrom(const FunDedicatedServerRpcMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunDedicatedServerRpcMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void FunDedicatedServerRpcMessage::Swap(FunDedicatedServerRpcMessage* other) {
  if (other != this) {
    std::swap(xid_, other->xid_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::google::protobuf::Metadata FunDedicatedServerRpcMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunDedicatedServerRpcMessage_descriptor_;
  metadata.reflection = FunDedicatedServerRpcMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

FunDedicatedServerRpcInfoMessage::FunDedicatedServerRpcInfoMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FunDedicatedServerRpcInfoMessage)
}

void FunDedicatedServerRpcInfoMessage::InitAsDefaultInstance() {
}

FunDedicatedServerRpcInfoMessage::FunDedicatedServerRpcInfoMessage(const FunDedicatedServerRpcInfoMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FunDedicatedServerRpcInfoMessage)
}

void FunDedicatedServerRpcInfoMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FunDedicatedServerRpcInfoMessage::~FunDedicatedServerRpcInfoMessage() {
  // @@protoc_insertion_point(destructor:FunDedicatedServerRpcInfoMessage)
  SharedDtor();
}

void FunDedicatedServerRpcInfoMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FunDedicatedServerRpcInfoMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunDedicatedServerRpcInfoMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunDedicatedServerRpcInfoMessage_descriptor_;
}

const FunDedicatedServerRpcInfoMessage& FunDedicatedServerRpcInfoMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_funapi_2frpc_2ffun_5fdedicated_5fserver_5frpc_5fmessage_2eproto();
  return *default_instance_;
}

FunDedicatedServerRpcInfoMessage* FunDedicatedServerRpcInfoMessage::default_instance_ = NULL;

FunDedicatedServerRpcInfoMessage* FunDedicatedServerRpcInfoMessage::New() const {
  return new FunDedicatedServerRpcInfoMessage;
}

void FunDedicatedServerRpcInfoMessage::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FunDedicatedServerRpcInfoMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FunDedicatedServerRpcInfoMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:FunDedicatedServerRpcInfoMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FunDedicatedServerRpcInfoMessage)
  return false;
#undef DO_
}

void FunDedicatedServerRpcInfoMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FunDedicatedServerRpcInfoMessage)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FunDedicatedServerRpcInfoMessage)
}

::google::protobuf::uint8* FunDedicatedServerRpcInfoMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FunDedicatedServerRpcInfoMessage)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FunDedicatedServerRpcInfoMessage)
  return target;
}

int FunDedicatedServerRpcInfoMessage::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunDedicatedServerRpcInfoMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FunDedicatedServerRpcInfoMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FunDedicatedServerRpcInfoMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunDedicatedServerRpcInfoMessage::MergeFrom(const FunDedicatedServerRpcInfoMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FunDedicatedServerRpcInfoMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunDedicatedServerRpcInfoMessage::CopyFrom(const FunDedicatedServerRpcInfoMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunDedicatedServerRpcInfoMessage::IsInitialized() const {

  return true;
}

void FunDedicatedServerRpcInfoMessage::Swap(FunDedicatedServerRpcInfoMessage* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FunDedicatedServerRpcInfoMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunDedicatedServerRpcInfoMessage_descriptor_;
  metadata.reflection = FunDedicatedServerRpcInfoMessage_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::FunDedicatedServerRpcMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::FunDedicatedServerRpcInfoMessage >, 11, false >
  ds_info(kDsInfoFieldNumber, ::FunDedicatedServerRpcInfoMessage::default_instance());

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
